name: ggplot2
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::r-base=4.2.3
  - conda-forge::r-ggplot2=3.5.1
  - conda-forge::r-gggenes=0.5.1
  - conda-forge::r-patchwork=1.2.0
  - conda-forge::r-optparse=1.7.5
