name: ggplot2
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::r-base=4.4.0
  - conda-forge::r-ggplot2=3.5.1
  - conda-forge::r-gggenes=0.5.1
  - conda-forge::r-gridtext=0.1.5
  - conda-forge::r-ggfittext=0.10.2
  - conda-forge::r-patchwork=1.3.0
  - conda-forge::r-optparse=1.7.5
